version: "3.9"

services:
  db:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  web:
    build:
      context: .
      args:
        - DATABASE_URL=postgres://postgres:postgres@db:5432 
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
    ports: 
      - 8080:3000
    depends_on:
      db:
        condition: service_started

