# fly.toml app configuration file generated for loathers-museum on 2023-11-27T15:13:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "loathers-museum"
primary_region = "lhr"

[build]

[deploy]
 release_command = "bun run db-init"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[processes]
  app = "bun run start"
  cron = "supercronic /app/crontab"

[[services]]
  processes = ["app"]