# fly.toml app configuration file generated for loathers-museum on 2023-11-28T14:32:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "loathers-museum"
primary_region = "lhr"

[build]

[deploy]
  release_command = "yarn run db-init"

[processes]
  app = "yarn run start"
  cron = "supercronic /app/crontab"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/healthcheck"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  processes = ["cron", "app"]
