import {
  sql,
  CREATE_COLLECTION_TABLE,
  CREATE_DAILY_COLLECTION_TABLE,
  CREATE_ITEM_TABLE,
  CREATE_PLAYER_NAME_CHANGE_TABLE,
  CREATE_PLAYER_TABLE,
} from "./db";

await sql.unsafe(CREATE_ITEM_TABLE);
await sql.unsafe(CREATE_PLAYER_TABLE);
await sql.unsafe(CREATE_PLAYER_NAME_CHANGE_TABLE);
await sql.unsafe(CREATE_COLLECTION_TABLE);
await sql.unsafe(CREATE_DAILY_COLLECTION_TABLE);
process.exit(0);
